name: jumpy_mvp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  http: ^1.3.0
  percent_indicator: ^4.2.4
  sensors_plus: ^6.1.1
  shared_preferences: ^2.5.2
  syncfusion_flutter_charts: ^28.2.11
  weather_animation: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  flutter_gen_runner:
  flutter_launcher_icons: 

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/launcher.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/power_animals/
    - assets/images/menu/
    - assets/images/jcons/
    - assets/images/users/

flutter_gen:
  integrations:
    flutter_svg: true